repos:
  # Base pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=20120]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=108]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=88"]

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          ["flake8-bugbear==23.9.16", "flake8-comprehensions==3.14.0"]

  # Non-Python formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: prettier (non-python)
        types_or: [yaml, json, markdown, html, css, scss, javascript]
        args: [--write, --ignore-unknown]
        additional_dependencies: ["prettier@3.0.3"]

  # Consistent file naming
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: prettier (filenames)
        args: [--write, --ignore-unknown]
        exclude: |
          (?x)^(
            \.venv|
            build|
            dist|
            node_modules
          )/
        files: \.(md|yaml|yml|json|js|ts|css|scss|html)$
