defaults:
  - model: default
  - data: default
  - training: default
  - inference: default
  - validation: default
  - _self_

hydra:
  run:
    dir: plots/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: train
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
